### ISSUE TITLE
Incompatible with latest go-ethereum v1.9.23

### ISSUE THREAD

**Issue by ryanc414** [ethersphere/swarm#2215]
#### System information

Swarm version: `0.5.7`
OS & Version: macOS Catalina 10.15.7

#### Expected behaviour

I would like to upgrade to the latest go-ethereum v1.9.23 in a project that also depends on ethersphere/swarm.

#### Actual behaviour

ethersphere/swarm does not compile with go-ethereum v1.9.23. It seems that the go-ethereum team must have made some non-semver breaking changes.

#### Steps to reproduce the behaviour

In an empty directory run:

```
$ go mod init example.com/m
go: creating new go.mod: module example.com/m
$ go get github.com/ethereum/go-ethereum
go: github.com/ethereum/go-ethereum upgrade => v1.9.23
$ go get github.com/ethersphere/swarm/contracts/ens/contract
```

Produces output below:

#### Backtrace

````
# github.com/ethersphere/swarm/contracts/ens/contract
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/ens.go:23:6: undefined: abi.U256
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/ens.go:158:46: cannot use result (type interface {}) as type *[]interface {} in argument to _ENS.Contract.ENSCaller.contract.Call: need type assertion
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/ens.go:177:36: cannot use result (type interface {}) as type *[]interface {} in argument to _ENS.Contract.contract.Call: need type assertion
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/ens.go:199:27: cannot use out (type *common.Address) as type *[]interface {} in argument to _ENS.contract.Call
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/ens.go:225:27: cannot use out (type *common.Address) as type *[]interface {} in argument to _ENS.contract.Call
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/ens.go:251:27: cannot use out (type *uint64) as type *[]interface {} in argument to _ENS.contract.Call
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/ensregistry.go:23:6: undefined: abi.U256
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/ensregistry.go:158:62: cannot use result (type interface {}) as type *[]interface {} in argument to _ENSRegistry.Contract.ENSRegistryCaller.contract.Call: need type assertion
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/fifsregistrar.go:23:6: undefined: abi.U256
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/publicresolver.go:23:6: undefined: abi.U256
../../../go/pkg/mod/github.com/ethersphere/swarm@v0.5.7/contracts/ens/contract/ensregistry.go:158:62: too many errors
````

**Comment by Eknir** [comment]
Hi @ryanc414 ,
Thanks for taking the time to make this issue.

Swarm is not anymore actively maintaining this project.

For your project, we recommend switching over to [bee](github.com/ethersphere/bee) ([documentation here](http://docs.ethswarm.org/)), which provides similar functionality to Swarm, but is build up anew from the grounds up, on more modern foundations, with more rigor during development and with the advancing insight which comes naturally while developing software like Swarm.

If you experience any difficulties with the porting of your code, we are more than happy to assist you.

You can reach out to me on Telegram (@eknir) or in the [BeeHive](beehive.ethswarm.org) (same user name), if you need assistance.

Best,

**Comment by ryanc414** [comment]
Thanks for the response! We actually only depend on the ens contract bindings at https://github.com/ethersphere/swarm/contracts/ens/contract, I couldn't find these in the bee repo you linked but it looks like we can use https://github.com/wealdtech/go-ens instead.
